{% snapshot users_ss %}

{{
    config(
      target_schema='snapshots',
      unique_key='id',
      strategy='check',
      check_cols=['ID','LAST_GEOCODED_STATE_CODE','FULL_CONTACT_DATA_UPDATED_AT','REFERRER_TOKEN','FC_INSTAGRAM_URL','COW_CASH_BALANCE_CENTS','UNSUBSCRIBED_ALL_AT','UTM_CAMPAIGN','VENDOR_ACCESS','FC_ID','FC_ANGELLIST_URL','FC_LINKEDIN_FOLLOWERS','ACCOUNT_BREACH_CHECKED_AT','REMEMBER_CREATED_AT','LAST_GEOCODED_CITY','LAST_GEOCODED_ADDRESS','VACATION_ENDS_AT','FC_JOB_TITLE','UNLOCK_TOKEN','ENCRYPTED_PASSWORD','LAST_SIGN_IN_IP','EMAIL_SUBSCRIBED_OFTEN_AT','LAST_GEOCODED_COUNTRY_CODE','UPDATED_AT','LAST_GEOCODED_STATE','REORDER_REMIND_DATE','FC_INSTAGRAM_FOLLOWERS','REFERRED_BY_USER_ID','FC_FAMILY_NAME','AFFILIATE_TRANSACTION_ID','REFERRER_URL','EMAIL','FC_ANGELLIST_FOLLOWERS','GENDER','RETENTION_OFFER_LAST_ACCEPTED_AT','LAST_GEOCODED_LONGITUDE','FC_TWITTER_URL','FC_IMAGE_URL','BANNED_AT','FC_GIVEN_NAME','FB_ID','BANNED_REASON','FC_TWITTER_FOLLOWERS','SUPPORT_STATE_UPDATED_AT','FC_BIO','RETENTION_OFFERS_ACCEPTED','UTM_TIME','UTM_CONTENT','ROLES_FOR_NOTIFICATIONS','LAST_GEOCODED_COUNTRY','TOKEN','CREATED_AT','CAMPAIGN_ID','UTM_SOURCE','CURRENT_SIGN_IN_AT','EMAIL_SUBSCRIBED_WEEKLY_AT','LANDING_PAGE_SOURCE','STRIPE_CUSTOMER_TOKEN','BANNED_BY_USER_ID','RESET_PASSWORD_TOKEN','UNCONFIRMED_EMAIL','NOTES_FOR_NEXT_ORDER','RESUBSCRIBED_AT','ADGROUP_ID','LAST_GEOCODED_POSTAL_CODE','FC_PINTEREST_FOLLOWERS','FAILED_ATTEMPTS','MERGED_INTO_USER_ID','MAILCHIMP_UNSUBSCRIBED_ALL_AT','TARGETID','EMAIL_VALIDATED_AT','RESET_PASSWORD_SENT_AT','PHONE_NUMBER_ID','EMAILS_PAUSED_UNTIL_DATE','CURRENT_SIGN_IN_IP','SIGN_IN_COUNT','FC_PINTEREST_URL','EMAIL_NAME','VIP_LEVEL','CREATIVEID','FC_COMPANY_NAME','PREDICTED_REORDER_DATE_UPDATED_AT','PREDICTED_REORDER_DATE','LOCKED_AT','ORIGINAL_URL','SUPPORT_STATE','FC_GENDER','FC_FULL_NAME','EXCLUDED_SHIPPING_CARRIERS','CONFIRMATION_TOKEN','UTM_MEDIUM','LAST_GEOCODED_IP_ADDRESS','ACTIVE_ORDER_ID','ACCOUNT_BREACH_RESET_PASSWORD_AT','FC_LINKEDIN_URL','PAY_RATE_CENTS','VACATION_BEGINS_AT','ZIP','LAST_SIGN_IN_AT','ALTERNATE_PHONE_NUMBER_ID','USER_TYPE','ROLES_FOR_ACCESS','LAST_GEOCODED_LATITUDE','EMAIL_VALIDATION_CODE','TEST_BUCKET','OPT_OUT_LIST','FC_FACEBOOK_URL','BANNED_FROM_REFERRALS','WAS_EMAIL_LEAD','OPTED_IN_TO_EMAILS','OPTED_IN_TO_SMS_MARKETING']
    )
}}

select * from {{ source('cc', 'users') }}

{% endsnapshot %}