name: dbt Docs Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt
      - name: Generate dbt docs
        env:
          DBT_CC_DATAWAREHOUSE_PROFILE: ${{secrets.DBT_CC_DATAWAREHOUSE_PROFILE}}
        run: |
          mkdir dbt_profile
          echo $DBT_CC_DATAWAREHOUSE_PROFILE >> dbt_profile/profiles.yml
          dbt docs generate --profiles-dir dbt_profile
      - name: Build the Docker image
        env:
          DBT_DOCS_PASSWORD: ${{ secrets.DBT_DOCS_PASSWORD }}
        run: |
          docker build -t crowdcow-dbt-docs --build-arg DBT_DOCS_PASSWORD=$DBT_DOCS_PASSWORD -f Dockerfile.dbtdocs .
