name: dbt Docs Docker Image CI

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install markupsafe==2.0.1
          pip install dbt-snowflake
      - name: Build the Docker image
        env:
          DBT_DOCS_PASSWORD: ${{ secrets.DBT_DOCS_PASSWORD }}
          DBT_CC_DATAWAREHOUSE_PROFILE: ${{secrets.DBT_CC_DATAWAREHOUSE_PROFILE}}
        run: |
          mkdir dbt_profile
          echo "$DBT_CC_DATAWAREHOUSE_PROFILE" > dbt_profile/profiles.yml
          dbt deps
          dbt docs generate --profiles-dir dbt_profile
          docker build -t crowdcow-dbt-docs --build-arg DBT_DOCS_PASSWORD=$DBT_DOCS_PASSWORD -f Dockerfile.dbtdocs .
      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1
          image: crowdcow-dbt-docs:latest
      - name: Deploy on Porter
        run: |
          curl -X POST 'https://dashboard.getporter.dev/api/webhooks/deploy/cba8da6b7c6c571bcea4634b2c2172a9?commit=latest'
